
[world_gen]

	#Customize ore lava crystal stone, obsidian, compressed world generation (in that order)
	[world_gen.lava_crystal]
		#Enable/Disable their world generation
		enable = [true, true, true]
		#Set the vein size
		vein_size = [5, 4, 3]
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		offset = [12, 6, 0]
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		range = [20, 10, 4]

	#Customize ore frost crystal stone, obsidian, compressed world generation (in that order)
	[world_gen.frost_crystal]
		#Enable/Disable their world generation
		enable = [true, true, true]
		#Set the vein size
		vein_size = [5, 4, 3]
		#Set the Y offset, Example: 
		#Offset: 4 - Sets the minimum Y height to 4.
		offset = [12, 6, 0]
		#Set the vein size, Example: 
		#Range: 8 - Sets the maximum Y height to 8.
		range = [20, 10, 4]

[advancements]
	#Enable/Disable the Thank You 6M advancement
	enableThankYou6M = true

[test]
	#Test: Please Ignore
	TEST = 1
	#Test List: Please Ignore
	_boolean = [true, true, false, true]
	#Test List: Please Ignore
	_int = [1, 2, 1, 3]
	#Enum Test: Please Ignore
	#Allowed Values: NONE, NIGHT_VISION, WATER_BREATHING, STRENGTH, SPEED, HASTE, JUMP_BOOST, REGENERATION, RESISTANCE, FIRE_RESISTANCE, SATURATION, INVISIBILITY, HEALTH_BOOST, ABSORPTION, SLOW_FALLING, FLIGHT, WITHER_IMMUNITY, WATER_WEAKNESS, FIRE_WEAKNESS, NATURAL_IMMUNITY
	_enum = "NONE"
	#Enum List Test: Please Ignore
	#Allowed Values: 
	#NONE, WITHER, SLOWNESS, BLINDNESS, NAUSEA, POISON, WEAKNESS, MINING_FATIGUE, HUNGER, GLOWING, LEVITATION, IGNITE
	_enum_list = ["NONE", "IGNITE"]

