#Add owner name to some messages
AddOwner = true
#Mob explosions can destroy blocks based on mob target
MobDestroy = false
#Chunks from world spawn
#Range: -1 ~ 5000
ChunksFromSpawn = 10
#Maximum claims per player
#Range: 0 ~ 250
ClaimLimit = 8
#Blocks that bypass claims on right click
BypassBlocks = ["minecraft:ender_chest", "waystones:sandy_waystore", "waystones:waystore", "waystones:mossy_waystore", "gravestore:gravestore"]


