command:
  # Message that you want to appear when the max tries of finding a safe location is reached [ placeholders: {playerName}, color codes: & + letter (example: &c) ].
  max-tries: '&cИстекло время попытки найти безопасное место, куда можно было бы переместиться.'
  # Message that you want to appear when the command is successfully made. [ placeholders: {playerName} {blockZ} {blockY}, color codes: & + letter (example: &c) ] [default: &aSuccessfully teleported you to a random location.]
  successfully: >-
    &aВы были телепортированы в координаты &e{blockX}, {blockY},
    {blockZ}&a.
  # Message that you want to appear when the command is on cooldown. [ placeholders: {playerName}, color codes: & + letter (example: &c) ] [default: &cWait more {secondsLeft} seconds for execute the command again.]
  cooldown: '&cПодождите еще {secondsLeft} секунд, чтобы снова выполнить команду.'
  # Message that you want to appear when you execute /rtpd with a dimension that is in the blacklist [ placeholders: {playerName} {dimensionId}, color codes: & + letter (example: &c) ]. [default: &cYou cannot random teleport to that dimension!]
  dimensionNotAllowed: '&cВы не можете случайным образом телепортироваться в это измерение!'